module ProjectSetup

export new_project

    using ..PipelineTypes
    using ..PipelineLog

    # Header written to every new pipeline.yml override file.
    const _PIPELINE_YML_HEADER = """
# Pipeline configuration overrides
# Add only the sections/keys you want to change relative to the parent level.
# Omitted settings are inherited from the nearest ancestor or from
# config/defaults/pipeline.yml (which lists all available options).
# This file is merged at runtime; delete it to inherit everything from above.
"""

    # pipeline.yml stubs written into data/ dirs. Comments explain the cascade role.

    const _STUDY_PIPELINE_YML = """
# Pipeline configuration - STUDY LEVEL
#
# Settings written here are the default for every run under this study.
# Place settings that define the study as a whole here: which primer pair
# was used, the target amplicon length range, the taxonomy database, etc.
#
# Leave a key out entirely to inherit the global (config/pipeline.yml)
# settings. Only write what you deliberately want to change.
#
# Any group- or run-level pipeline.yml beneath this directory can override
# these values further.
"""

    const _GROUP_PIPELINE_YML = """
# Pipeline configuration - GROUP LEVEL
#
# Settings written here apply to all runs in this sub-directory and take
# precedence over the study-level file above.
#
# Use this when a subset of runs share settings that differ from the rest
# of the study (e.g. a different sequencing batch or primer set).
#
# Leave a key out entirely to inherit from the study level. Only write
# what you deliberately want to change.
"""

    const _RUN_PIPELINE_YML = """
# Pipeline configuration - RUN LEVEL
#
# Settings written here apply to this single run only and take precedence
# over every level above.
#
# Leave a key out entirely to inherit from the group or study level. Only
# write what you deliberately want to change.
#
# The fully-merged result of every cascade level is written to
# projects/{study}/{run}/run_config.yml at runtime. That file is the
# authoritative record of exactly what configuration was used.
"""

    const _GLOBAL_CONFIGS_MD = """
# Global Configuration

In this directory is the machine-level override. Anything written here
applies to every study run on this installation, regardless of project.

This is the right place for settings that reflect the environment: which
remote server handles taxonomy assignment, how many threads this machine
can spare, as well as primers available to be picked by cutadapt.

Leave a key out entirely to inherit the default. Only write what you
deliberately want to change.

Note that this is the lowest-precedence level after the defaults. Any
setting written here can be overridden at the project, group, or run
level, this simply serves as the fallback for every run that does not
explicitly override it.

**WARNING: This file was regenerated by project.jl**
"""

    const _DEFAULT_CONFIGS_MD = """
# Default Configuration

In this directory is the baseline for every pipeline run on every
machine. It lists every key the pipeline understands and supplies a
sensible starting value for each one.

Do not edit this file unless you are a contributer. It is the
software's own definition of what a complete configuration looks like.
Changes here will be overwritten on update.

To change a setting, add it to the appropriate level above this one -
e.g: `config/pipeline.yml` for machine-wide changes, or a project- or
run-level file for narrower scope.

**WARNING: This file was regenerated by project.jl**
"""

    # Write a file if it does not already exist.
    function _create_if_absent(path::String, content::String)
        if !isfile(path)
            write(path, content)
            @info "Created: $path"
        end
    end

    """
        new_project(name; data_dir, projects_dir, config_dir)

    Bootstrap a project for the study named `name`.

    Pipeline configuration stubs (`pipeline.yml`) are created inside the data
    tree (`data_dir/{name}/`) so that inputs and their settings are co-located.
    Edit those files before (re-)running the pipeline. Omitted keys inherit from
    the nearest ancestor, falling back to `config/defaults/pipeline.yml`.

    Output directories are created under `projects_dir/{name}/` mirroring the
    data layout. They contain only pipeline outputs and the auto-generated
    `run_config.yml` (the fully-merged configuration actually used).

    `databases.yml`, `tools.yml`, and `primers.yml` are copied from
    `config/defaults/` on first run (edit them in place; they are not cascaded).

    Re-running `new_project` never overwrites existing files.

    Returns a `Vector{ProjectCtx}`, one per leaf run.
    """
    function new_project(name::String;
                         data_dir::String     = "./data",
                         projects_dir::String = "./projects",
                         config_dir::String   = "./config")

        defaults_dir = joinpath(config_dir, "defaults")
        root_data    = joinpath(data_dir, name)
        root_project = joinpath(projects_dir, name)

        isdir(root_data) || error("Data directory not found: $root_data")

        # Bootstrap standalone configs (not cascade-merged) from defaults.
        for fname in ("databases.yml", "tools.yml", "primers.yml")
            dst = joinpath(config_dir, fname)
            if !isfile(dst)
                src = joinpath(defaults_dir, fname)
                isfile(src) || error("Default template not found: $src")
                cp(src, dst)
                @info "Created: $dst"
            end
        end

        # Bootstrap config/ level docs and pipeline.yml stub.
        _create_if_absent(joinpath(config_dir, "pipeline.yml"),        _PIPELINE_YML_HEADER)
        _create_if_absent(joinpath(config_dir, "global_configs.md"),   _GLOBAL_CONFIGS_MD)
        _create_if_absent(joinpath(defaults_dir, "default_configs.md"), _DEFAULT_CONFIGS_MD)

        # Find leaf directories (those containing .fastq.gz), relative to root_data.
        leaf_relpaths = String[]
        for (dirpath, _, files) in walkdir(root_data; follow_symlinks=true)
            if any(f -> endswith(f, ".fastq.gz"), files)
                push!(leaf_relpaths, relpath(dirpath, root_data))
            end
        end
        isempty(leaf_relpaths) && error("No .fastq.gz files found under $root_data")

        # Collect all data-tree dirs that need a pipeline.yml stub.
        leaf_data_dirs = Set(rp == "." ? root_data : joinpath(root_data, rp)
                             for rp in leaf_relpaths)

        all_data_dirs = Set{String}([root_data])
        for rp in leaf_relpaths
            rp == "." && continue
            parts = splitpath(rp)
            for i in 1:length(parts)
                push!(all_data_dirs, joinpath(root_data, parts[1:i]...))
            end
        end

        # Write pipeline.yml stubs into data/ (top-down so parents exist first).
        sorted_data_dirs = sort(collect(all_data_dirs), by = d -> length(splitpath(d)))
        for dir in sorted_data_dirs
            yml_content = if dir in leaf_data_dirs
                _RUN_PIPELINE_YML
            elseif dir == root_data
                _STUDY_PIPELINE_YML
            else
                _GROUP_PIPELINE_YML
            end
            _create_if_absent(joinpath(dir, "pipeline.yml"), yml_content)
        end

        # Create output directories in projects/ (no pipeline.yml written here).
        for rp in leaf_relpaths
            proj_dir = rp == "." ? root_project : joinpath(root_project, rp)
            mkpath(proj_dir)
        end

        # Return one ProjectCtx per leaf.
        projects = ProjectCtx[]
        for rp in leaf_relpaths
            proj_dir  = rp == "." ? root_project : joinpath(root_project, rp)
            fastq_dir = rp == "." ? root_data    : joinpath(root_data,    rp)
            ctx = ProjectCtx(proj_dir, config_dir, fastq_dir, root_project, root_data)
            pipeline_log(ctx, "Project initialised")
            push!(projects, ctx)
        end
        @info "$(length(projects)) project(s) ready under $root_project"
        return projects
    end

end
