#!/usr/bin/env bash
# SPDX-License-Identifier: MPL-2.0
# SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
#
# gen-tools-yml.sh — codegen for config/tools.yml (machine-specific,
# gitignored). Makes a fresh clone runnable with zero manual configuration:
# after `just bootstrap` the pipeline's tool map already matches the machine.
#
# Rule per tool, in precedence order (documented in docs/reproducibility.md):
#   bare name   - a binary found on PATH (inside a guix shell or another
#                 managed env): resolved at pipeline runtime from PATH;
#                 pipeline preflight asserts its VERSION against
#                 config/defaults/tool_versions.yml, so a wrong version on
#                 PATH fails loudly there, never silently.
#   null        - nothing on PATH: the managed download lane (install.sh
#                 fetches the sha256-pinned archive from tool_versions.yml
#                 into bin/) remains the byte-exact authority.
# Absolute local paths and user@host SSH paths stay manual (edit the
# generated file; this script never overwrites a hand-edited entry whose
# value is neither null nor a bare name it would have written).
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="config/tools.yml"
mkdir -p config

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  printf '# SPDX-License-Identifier: AGPL-3.0-only\n'
  printf '# GENERATED by scripts/gen-tools-yml.sh on %s — machine-specific;\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u)"
  printf '# gitignored; regenerate with: just codegen\n'
  printf '# Template: config/defaults/tools.yml (committed). Rules: bare name =\n'
  printf '# PATH lookup (guix/managed env), null = sha256-pinned download lane.\n'
  printf '\n'
} > "$tmp"

write_tool() {
  local key="$1" bin="$2"
  printf '%s:\n' "$key" >> "$tmp"
  if command -v "$bin" >/dev/null 2>&1; then
    printf '  path: "%s"  # on PATH (%s)\n\n' "$bin" "$(command -v "$bin")" >> "$tmp"
  else
    printf '  path: null  # managed download (install.sh, sha256-pinned)\n\n' >> "$tmp"
  fi
}

write_tool cutadapt   cutadapt
write_tool fastqc     fastqc
write_tool multiqc    multiqc
write_tool vsearch    vsearch
write_tool swarm      swarm
write_tool cd_hit_est cd-hit-est

mv -f "$tmp" "$OUT"
printf 'gen-tools-yml: wrote %s\n' "$OUT"
resolved=$(grep -c 'path: "' "$OUT" || true)
printf 'gen-tools-yml: %s tools resolved from PATH (rest: sha256-pinned download lane)\n' "$resolved"
exit 0
