seed: 123
subsample_n: 0
pool_children: false
dada2:
  merge:
    max_mismatch: 0
    min_overlap: 20
    trim_overhang: true
  asv:
    denovo_method: "consensus"
    band_size_max: 430
    band_size_min: 200
  output:
    taxa_prefix: "taxonomy"
    fasta_prefix: "asvs"
    seq_table_prefix: "seqtab_nochim"
  verbose: true
  filter_trim:
    min_len: 175
    max_n: 0
    match_ids: true
    rm_phix: true
    trunc_q: 2
    trunc_len:
      - 220
      - 220
    max_ee:
      - 3
      - 3
  file_patterns:
    mode: "paired"
  taxonomy:
    remote:
      host: ~
      rscript: "Rscript"
      staging_dir: "/absolute/path/on/server"
      identity_file: ~
    min_boot: 0
    enabled: true
    multithread: 4
    database: "pr2"
  dada:
    max_consist: 15
    pool_method: "pseudo"
    nbases: 200000000
merge_taxa: ~
fastqc:
  threads: 20
  optional_args: ""
analysis:
  alpha:
    annotate_significance: false
    metrics:
      - "richness"
      - "shannon"
      - "simpson"
    pairwise_brackets: false
    paired_samples: false
    show_points: true
    significance_test: "kruskal_wallis"
  nmds:
    max_stress: 0.2
cutadapt:
  r1_suffix: "_R1"
  r2_suffix: "_R2"
  error_rate: ~
  primer_pairs:
    - "EMP"
  discard_untrimmed: true
  cores: 0
  min_length: 200
  optional_args: ""
  overlap: ~
  quality_cutoff: ~
swarm:
  threads: 0
  chimera_check: true
  differences: 1
  fastq_minovlen: 20
  enabled: true
  min_abundance: 2
  identity: 0.97
  optional_args: ""
vsearch:
  query_cov: 0.8
  maxrejects: ~
  maxaccepts: ~
  enabled: true
  identity: 0.75
  strand: ~
  optional_args: ""
cdhit:
  threads: 0
  enabled: false
  identity: 0.97
  optional_args: ""
multiqc:
  optional_args: ""
