# Kandaurova, E. (2025) 'Metabarcoding of gut protists of Eurasian beaver'.
# Owens, L.A., Friant, S., Martorelli Di Genova, B., Knoll, L.J., Contreras, M., Noya-Alarcon, O., Dominguez-Bello, M.G., and Goldberg, T.L. (2024) 'VESPA: an optimized protocol for accurate metabarcoding-based characterization of vertebrate eukaryotic endosymbiont and parasite assemblages', Nature Communications, 15(1), 402, available: https://doi.org/10.1038/s41467-023-44521-3.

Forward:
  TarEukF: "CCAGCASCYGCGGTAATTCC"
  ArchF: "YGCGGTAAYTCCAGCTC"
  VESPAF: "AGCAGCCGCGGTAATTCC"

Reverse:
  TarEukR: "ACTTTCGTTCTTGATYRA"
  Meta1R: "CYCCTACYYTMGYYCTKGA"
  Meta2R: "DCTKTCGTYCTTGATYRA"
  VESPAR: "TCCGTCAATTYCTTNAASTTTC"

Pairs:
  - TarEuk:
    - TarEukF
    - TarEukR
  - Meta1:
    - TarEukF
    - Meta1R
  - Meta2:
    - TarEukF
    - Meta2R
  - Arch:
    - ArchF
    - TarEukR
  - VESPA:
    - VESPAF
    - VESPAR