Forward:
  # Earth Microbiome Project 16S V4 (Parada/Apprill, 2016)
  EMP515F: "GTGYCAGCMGCCGCGGTAA"

Reverse:
  # Earth Microbiome Project 16S V4 (Parada/Apprill, 2016)
  EMP806R: "GGACTACNVGGGTWTCTAAT"

Pairs:
  - EMP:
    - EMP515F
    - EMP806R
