# Saved from table Protist_Filtered
filters:
  - column: "Domain_boot"
    type: "min"
    value: 100
  - column: "Supergroup_boot"
    type: "min"
    value: 100
  - column: "Division_boot"
    type: "min"
    value: 100
  - column: "Subdivision_boot"
    type: "min"
    value: 100
  - column: "Class_boot"
    type: "min"
    value: 80
  - column: "Order_boot"
    type: "min"
    value: 80
  - column: "Family_boot"
    type: "min"
    value: 80
  - column: "Genus_boot"
    type: "min"
    value: 80
