module ProjectSetup

export new_project

    using ..PipelineTypes

    # Header written to every new pipeline.yml override file.
    const _PIPELINE_YML_HEADER = """
# Pipeline configuration overrides
# Add only the sections/keys you want to change relative to the parent level.
# Omitted settings are inherited from the nearest ancestor or from
# config/defaults/pipeline.yml (which lists all available options).
# This file is merged at runtime; delete it to inherit everything from above.
"""

    # pipeline.yml stubs written at each project level. Comments explain the
    # cascade role so users have context without needing a separate docs file.

    const _PROJECT_PIPELINE_YML = """
# Pipeline configuration overrides - PROJECT LEVEL
#
# Settings written here serve as the default for every run under this
# study; any group- or run-level file can override them further.
#
# This is the right place for choices that define the study as a whole:
# which primer set was used, the target amplicon length range, or the
# taxonomy database for this organism group.
#
# Leave a key out entirely to inherit the global settings unchanged. Only
# write what you deliberately want to change.
#
# Note that this level is overridden by any group or run beneath it; it
# simply serves as the fallback for every run that does not explicitly
# override it.
"""

    const _GROUP_PIPELINE_YML = """
# Pipeline configuration overrides - GROUP LEVEL
#
# Settings written here serve as the default for all runs nested beneath
# this directory; any run-level file can override them further.
#
# Use it when a subset of runs within the study share settings that differ
# from the study defaults - for example, if one batch of samples was
# sequenced with different conditions or from collected different locations.
#
# Leave a key out entirely to inherit the study settings unchanged. Only
# write what you deliberately want to change.
#
# Note that this level is overridden by any run beneath it; it simply
# serves as the fallback for every run that does not explicitly override it.
"""

    const _RUN_PIPELINE_YML = """
# Pipeline configuration overrides - RUN LEVEL
#
# Settings written here apply to this single run only and take precedence
# over every level above.
#
# Use it when runs within the study differ from one another - for example,
# if one batch of samples was sequenced with different conditions or from
# collected different locations.
#
# Leave a key out entirely to inherit the group or study settings unchanged.
# Only write what you deliberately want to change.
#
# run_config.yml in this same directory is generated automatically at
# runtime. It shows the fully merged result of every cascade level and is
# the single place to see the complete configuration that was actually used.
# Do not edit it; it is overwritten on each run.
"""

    const _GLOBAL_CONFIGS_MD = """
# Global Configuration

In this directory is the machine-level override. Anything written here
applies to every study run on this installation, regardless of project.

This is the right place for settings that reflect the environment: which
remote server handles taxonomy assignment, how many threads this machine
can spare, as well as primers available to be picked by cutadapt.

Leave a key out entirely to inherit the default. Only write what you
deliberately want to change.

Note that this is the lowest-precedence level after the defaults. Any
setting written here can be overridden at the project, group, or run
level, this simply serves as the fallback for every run that does not
explicitly override it.

**WARNING: This file was regenerated by project.jl**
"""

    const _DEFAULT_CONFIGS_MD = """
# Default Configuration

In this directory is the baseline for every pipeline run on every
machine. It lists every key the pipeline understands and supplies a
sensible starting value for each one.

Do not edit this file unless you are a contributer. It is the
software's own definition of what a complete configuration looks like.
Changes here will be overwritten on update.

To change a setting, add it to the appropriate level above this one -
e.g: `config/pipeline.yml` for machine-wide changes, or a project- or
run-level file for narrower scope.

**WARNING: This file was regenerated by project.jl**
"""

    # Write a file if it does not already exist.
    function _create_if_absent(path::String, content::String)
        if !isfile(path)
            write(path, content)
            @info "Created: $path"
        end
    end

    """
        new_project(name; data_dir, projects_dir, config_dir)

    Bootstrap a project tree under `projects_dir/{name}/` mirroring the
    directory structure found under `data_dir/{name}/`.

    Any directory within `data_dir/{name}/` that contains `.fastq.gz` files is
    treated as a leaf run. The study root and all intermediate directories each
    receive an empty `pipeline.yml` override stub and a `*_configs.md` file
    explaining that level's role in the cascade. Users add only the settings
    they want to change; everything else is inherited from the nearest ancestor,
    falling back to `config/defaults/pipeline.yml`.

    `databases.yml` and `tools.yml` are copied from `config/defaults/` on first
    run (they are not part of the cascade -- edit them in place).

    Re-running `new_project` never overwrites existing files.

    Returns a `Vector{ProjectCtx}`, one per leaf run.
    """
    function new_project(name::String;
                         data_dir::String     = "./data",
                         projects_dir::String = "./projects",
                         config_dir::String   = "./config")

        defaults_dir = joinpath(config_dir, "defaults")
        root_data    = joinpath(data_dir, name)
        root_project = joinpath(projects_dir, name)

        isdir(root_data) || error("Data directory not found: $root_data")

        # Bootstrap standalone configs (not cascade-merged) from defaults.
        for fname in ("databases.yml", "tools.yml", "primers.yml")
            dst = joinpath(config_dir, fname)
            if !isfile(dst)
                src = joinpath(defaults_dir, fname)
                isfile(src) || error("Default template not found: $src")
                cp(src, dst)
                @info "Created: $dst"
            end
        end

        # Bootstrap config/ level docs and pipeline.yml stub.
        _create_if_absent(joinpath(config_dir, "pipeline.yml"),   _PIPELINE_YML_HEADER)
        _create_if_absent(joinpath(config_dir, "global_configs.md"),   _GLOBAL_CONFIGS_MD)
        _create_if_absent(joinpath(defaults_dir, "default_configs.md"), _DEFAULT_CONFIGS_MD)

        # Find leaf directories (those containing .fastq.gz), relative to root_data.
        leaf_relpaths = String[]
        for (dirpath, _, files) in walkdir(root_data)
            if any(f -> endswith(f, ".fastq.gz"), files)
                push!(leaf_relpaths, relpath(dirpath, root_data))
            end
        end
        isempty(leaf_relpaths) && error("No .fastq.gz files found under $root_data")

        # Classify every project directory by its role in the cascade.
        leaf_dirs = Set(rp == "." ? root_project : joinpath(root_project, rp)
                        for rp in leaf_relpaths)

        all_dirs = Set{String}([root_project])
        for rp in leaf_relpaths
            rp == "." && continue
            parts = splitpath(rp)
            for i in 1:length(parts)
                push!(all_dirs, joinpath(root_project, parts[1:i]...))
            end
        end

        # Process top-down so each level can serve as source for its children.
        sorted_dirs = sort(collect(all_dirs), by = d -> length(splitpath(d)))

        for dir in sorted_dirs
            mkpath(dir)
            yml_content = if dir in leaf_dirs
                _RUN_PIPELINE_YML
            elseif dir == root_project
                _PROJECT_PIPELINE_YML
            else
                _GROUP_PIPELINE_YML
            end
            _create_if_absent(joinpath(dir, "pipeline.yml"), yml_content)
        end

        # Return one ProjectCtx per leaf, with study_dir = root_project.
        projects = ProjectCtx[]
        for rp in leaf_relpaths
            proj_dir  = rp == "." ? root_project : joinpath(root_project, rp)
            fastq_dir = rp == "." ? root_data    : joinpath(root_data,    rp)
            push!(projects, ProjectCtx(proj_dir, config_dir, fastq_dir, root_project))
        end
        @info "$(length(projects)) project(s) ready under $root_project"
        return projects
    end

end
